Recipe App
lenkon/Recipe-app pull request #25
Opened 2023-09-08 21:41 UTC by lenkon

#### The following are implemented:
- Login page and registration page:
- Built with Devise.
- Food list:
  - Display a list of food added by the logged-in user.
  - Add a form to allow users to add new food.
- Recipes list:
  - Display a list of recipes created by the logged-in user.
  - Show recipe details.
  - Delete the function of recipe if the user is the owner.
- Public recipe list:
  - Display a list of all public recipes ordered by newest.
  - Show recipe details.
- Recipe details:
  - If the recipe is public or the user is the owner of the recipe, should display the recipe details.
  - If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
- General shopping list view (only for a group that has less than 3 members):
  - Show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
  - Count the total food items and total price of the missing food.
- Solved N+1 queries problem.
- Created a navigation menu that allows users to open all of the pages created.

2023-09-08 23:53 UTC, OyePriscilla requested changes
Hi @lenkon and @musangamfure 👏 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Use Ruby gems as a software packages system. ✔️ 
Use params from browser requests in a safe way. ✔️
Use preprocessed HTML file with embedded Ruby code. ✔️
Use database migration files to maintain database schema. ✔️
Use validations for models. ✔️
Secure app from n+1 problems. ✔️
Set up associations between models. ✔️
Build a web app that requires the user to log in. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 23:53 UTC, OyePriscilla commented on config/routes.rb
> +end
- [ ] Please kindly remove all the commented code, this will make your codebase to be neat and cleaner. 👍

2023-09-08 23:53 UTC, OyePriscilla commented on app/controllers/foods_controller.rb
> +  end
- [ ] Please in accordance to the project requirement. kindly create success and fail paths for create and destroy actions. Implementing this will make your app to be fully engaging and communicative. ✔️ **Hint: You did it perfectly  in recipe_foods_controller.rb (for create and update actions.)**

2023-09-08 23:53 UTC, OyePriscilla commented on app/controllers/recipe_foods_controller.rb
> +  end
- [ ] Please kindly create success and fail paths for the destroy action, this will reduce the brittleness of your view and make your code easier to understand. ℹ️

2023-09-08 23:53 UTC, OyePriscilla commented on app/controllers/recipes_controller.rb
> +  end
- [ ] Please kindly create fail path for the destroy action, this will reduce the brittleness of your view and make your code easier to understand. ℹ️

2023-09-08 23:53 UTC, OyePriscilla commented on app/views/layouts/_nav.html.erb
> +          </li>
- [ ] Kindly add the generate shopping list link to the navigation items, as stated in the project requirement. ✔️
 
![Code review](https://github.com/lenkon/Recipe-app/assets/103386183/836e54c2-cd3c-4278-8d54-37e3377a8613)

2023-09-08 23:53 UTC, OyePriscilla commented on app/views/recipes/_add_modal.html.erb
> +        <div class="col-md-3 d-flex justify-content-end">
- [ ] In accordance to the wireframe, kindly adjust the Shopping List's route. It should link to the Shopping list's index page and not recipe_foods' index page. ℹ️ 
## Your implementation
![Code review](https://github.com/lenkon/Recipe-app/assets/103386183/02233e63-c5be-4fc9-964e-8ebcf1cbb949)

## Wireframe
![Code review](https://github.com/lenkon/Recipe-app/assets/103386183/7cd0f480-26db-46e9-9998-660c069b4083)

2023-09-09 05:07 UTC, lenkon commented
Hi @OyePriscilla ,

Thanks for the feedback and the change request. I have made the required changes.

Best Regards,
K. Inoulen Shanongba

2023-09-09 05:38 UTC, rloterh commented on config/routes.rb
> +end
well resolved! ✔️

2023-09-09 05:49 UTC, rloterh commented on app/controllers/foods_controller.rb
> +  end
well resolved! ✔️

2023-09-09 05:52 UTC, rloterh commented on app/controllers/recipes_controller.rb
> +  end
well resolved! ✔️

2023-09-09 05:59 UTC, rloterh commented on app/views/layouts/_nav.html.erb
> +          </li>
well resolved! ✔️

2023-09-09 05:59 UTC, rloterh commented on app/views/recipes/_add_modal.html.erb
> +        <div class="col-md-3 d-flex justify-content-end">
well resolved! ✔️

2023-09-09 06:03 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Inoulen & Emmanuel,  

**RoR group project** is complete! 🏁 Great job!🥇🥇 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Awesome job on introducing improvements to the Recipe app!
🎲 ReadMe looks good!

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-09 06:06 UTC, merged